name: Windows build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_package:
    name: Build nuget package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build native libraries
      run: sh ./lib/Windows/buildLibmtp.sh
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build ./lib/Windows/LibMtpSharp.Native.Windows.WithDependencies/LibMtpSharp.Native.Windows.WithDependencies.csproj
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: windows_packages
        path: ./lib/packages/LibMtpSharp.Native.Windows.*.nupkg
